name: goreleaser

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: server/go.mod
          check-latest: true
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: client/package-lock.json
      - name: Install npm dependencies and run script
        run: |
          cd client
          npm install
          npm run build:fast
          npm run build:slow
          mv dist/ ../server/static
      - name: Install go dependencies
        run: |
          cd server
          go mod vendor
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # 'latest', 'nightly', or a semver
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
